### ISSUE TITLE
Use TypedLua definition files

### ISSUE THREAD

**Issue by Zash** [mpeterv/luacheck#137]
This may be out of scope and/or overlap with #129 but I would very much like to have something that understood [TypedLua definition files](https://github.com/andremm/typedlua/blob/master/examples/bootstrap/base.tld) and pointed out violations.

**Comment by mpeterv** [comment]
Do you mean that luacheck should find type errors according to these definition files? Isn't is the role of TypedLua itself to do that? If you mean that luacheck should simply allow working with globals listed in the definition file it could be useful to avoid duplication of custom globals in TypedLua definition and .luacheckrc.

**Comment by Zash** [comment]
I'm basically looking for a way to get some of the benefits of static typing without the need to rewrite a large codebase in a statically typed language. As I said, it might be out of scope for luacheck.

**Comment by mpeterv** [comment]
I like the idea of some less strict type checking that prioritizes avoiding false positives, using type annotations more as hints rather than assertions. However, it's indeed out with of scope for luacheck IMO. Even if at some point luacheck gets this type of type checking then it'll probably have its own definition format.
