### ISSUE TITLE
Support Visual Studio report format?

### ISSUE THREAD

**Issue by Alloyed** [mpeterv/luacheck#142]
So Visual Studio proper (not VSCode) has a way to use external linters, but it insists on its own unique report type, loosely described here:

https://blogs.msdn.microsoft.com/msbuild/2006/11/02/msbuild-visual-studio-aware-error-messages-and-message-formats/

Any chance to get a new formatter for this?

**Comment by mpeterv** [comment]
@Alloyed implemented on master branch as `--formatter visual_studio`. Some things are done sub-optimally in accordance to the newer, more strict docs. The latest version appears to be this: https://docs.microsoft.com/en-us/cpp/ide/formatting-the-output-of-a-custom-build-step-or-build-event

* Column ranges are not provided for regular warnings/errors.
* File name put inside error message instead of the normal place for fatal errors like I/O, since the new docs require at least a line number when providing a file name properly.

Unless there is immediate feedback I'm going to release 0.22.0 with this as is, can improve later.

**Comment by Alloyed** [comment]
Yep, I can confirm this works <3
In my case, using visual studio 2015, the visual studio editor doesn't have a way of representing column ranges anyway, so just the first offset is more than fine.
