### ISSUE TITLE
Add (optional) rule to check consistency of indentation?

### ISSUE THREAD

**Issue by alexdowad** [mpeterv/luacheck#223]
Thank you for luacheck! It is a very nice tool.

Are you interested in adding a rule to check that indentation is consistent; for example, that only tabs or only spaces are used? Probably this would be disabled by default, to avoid breaking existing users.

If you like the idea, I would be happy to send a PR.

**Comment by alerque** [comment]
FYI, this repository is sadly defunct because the original author sadly passed away and nobody has a way to manage it. The defacto replacement fork is [lunarmodules/luacheck](https://github.com/lunarmodules/luacheck). Can I ask that you close this issue and re-open a new one there. As one of the current maintainers I have some thoughts on this, but I think it would be better to have that discussion on the active fork repository. Thanks!

**Comment by alexdowad** [comment]
Understood.

**Comment by alexdowad** [comment]
Just looked at your fork, and it looks like some really nice work has been done since it was created.

I have opened an issue on the Alpine Linux bug tracker suggesting that AL should move to packaging your fork.

**Comment by alerque** [comment]
Just a note in case some packager is confused, the fork I linked is the canonical home of the continuation of this project, but the fork actually started out life nested in the luarocks GitHub org and the latest LuaRocks release still links there. We haven't cut a new release since moving the fork from the LuaRocks org (where it didn't really fit) to the lunarmodules org, but we'll probably do that soon.

**Comment by alexdowad** [comment]
> Just a note in case some packager is confused, the fork I linked is the canonical home of the continuation of this project, but the fork actually started out life nested in the luarocks GitHub org and the latest LuaRocks release still links there. We haven't cut a new release since moving the fork from the LuaRocks org (where it didn't really fit) to the lunarmodules org, but we'll probably do that soon.

The Alpine Linux package for luacheck pulls the source code from https://github.com/mpeterv/luacheck/archive.

If you have any suggestion on what the best URL is for packagers to pull the project source, please share.

**Comment by alerque** [comment]
@alexdowad A download either from LuaRocks or from the lunarmodules/luacheck repository tag is fine. Which is better depends a little bit on how the packaging system works, whether it is using `luarocks make` or just cobbling together a build itself, etc.
