### ISSUE TITLE
[Question] E011: Expected `do` near `B10000000`

### ISSUE THREAD

**Issue by kylechui** [mpeterv/luacheck#226]
Hi there, I've written a short snippet of Lua and I can't seem to understand why luacheck keeps throwing this error on the first line:
```lua
while byte >= 0B10000000 and byte < 0B11000000 do
    pos[2] = pos[2] - 1
    byte = string.byte(M.get_line(pos[1]):sub(pos[2], pos[2]))
end
```
![image](https://user-images.githubusercontent.com/48545987/184232597-8a4ce453-e41d-40e7-a415-79e95995d67f.png)

Any help would be appreciated, and thanks for writing such a great piece of software!

**Comment by alerque** [comment]
Per #198 the canonical upstream repository for this project is now https://github.com/lunarmodules/luacheck. Please close this issue (since nobody else with permissions can do so here) and copy this content to a new issue on the Lunarmodules repo. Also include the output of `luacheck --version` in your report.

**Comment by kylechui** [comment]
Ah, sorry about that. I'll do so right now
