### ISSUE TITLE
Config not searched in `$XDG_CONFIG_HOME` on macOS

### ISSUE THREAD

**Issue by erikw** [mpeterv/luacheck#231]
First, thanks for this great tool. I recently started using it together with NeoVim and it works splendid!

As [documented](https://luacheck.readthedocs.io/en/stable/config.html#configuration-file), the config file is on macOS looked for in `$HOME/Library/Application\ Support/Luacheck` and not in the XDG path `$XDG_CONFIG_HOME/luacheck`.

macOS is also a modern Unix-like/based system and it would make sense to look for the config file in the XDG Path if not found in the Library path. I manage my config files in a dotfiles repo and have everything in `~/.config` that supports this. I think many developers in macOS also utilize the XDG paths.

In my case this meant that in the NeoVim plugin ALE I had to configure luacheck with extra options:

```lua
 vim.g.ale_lua_luacheck_options = "--config $XDG_CONFIG_HOME/luacheck/.luacheckr"
```
This should not be needed.

The code that would need update is here:
https://github.com/mpeterv/luacheck/blob/7360cfb4cf2c7dd8c73adf45e31a04811a745250/src/luacheck/config.lua#L31-L37

If not finding a config in the Library path, the same logic that is currently in the `else` clause should be done in the Darwin case

**Comment by alerque** [comment]
This is not the right repository to report this — the canonical repository for LuaCheck is [now under lunarmodules](https://github.com/lunarmodules/luacheck). See #198 for background. I would request you close this issue (since nobody else has access to do so) and open a new one on the canonical repository (assuming this is an issue in the current version, v1.1.0). Contributions are welcome, this sounds like a reasonable suggestion.

**Comment by erikw** [comment]
Oh dear 😢  @alerque 

Thank you for the sharing (the very sad news). I re-posted it here:

https://github.com/lunarmodules/luacheck/issues/88
